# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Javascript client CI

on:
  push:
    paths: clients/javascript/**
    branches: [ "master" ]
  pull_request:
    paths: clients/javascript/**
    branches: [ "master" ]

jobs:
  build-javascript-client:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm install
      working-directory: ${{ github.workspace }}/clients/javascript
    - run: npm run build
      working-directory: ${{ github.workspace }}/clients/javascript
    - name: publish server to npm
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_PASSWORD }}
        package: ${{ github.workspace }}/clients/javascript/build/package.json
        check-version: true
